# Generated by Django 4.0.4 on 2022-06-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laptops',
            new_name='Laptop',
        ),
    ]
